run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - bodyclose
    - misspell
    - unconvert
    - predeclared
    - noctx
    - nolintlint
    - exportloopref
    - goconst
    - gocritic
    - gosec
    - revive

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  revive:
    rules:
      - name: exported
      - name: unused-parameter
      - name: indent-error-flow
      - name: error-return
      - name: error-naming
      - name: error-strings
      - name: dot-imports
      - name: blank-imports
  gosec:
    excludes:
      - G104
      - G107

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - goconst
        - gocritic
    - path: migrations/
      linters:
        - gosec
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true